trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core SDK 2.2.401 (Global Tools error workaround)'
  inputs:
    version: 2.2.401

- task: DotNetCoreCLI@2
  displayName: 'Install GitVersion (Global Tools Linux Build Agent Workaround)'
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install -g GitVersion.Tool'

- script: 'dotnet-gitversion /output buildserver /nofetch' 
  displayName: 'Run GitVersion'

- task: GitHubTag@1
  displayName: 'Tag Git'
  inputs:
    githubEndpoint: 'corvus-dotnet-github'
    repositoryName: 'corvus-dotnet/Corvus.Extensions'
    commmit: 'Release v$(GitVersion.MajorMinorPatch)'
    tag: '$(GitVersion.MajorMinorPatch)'